FROM python:3.10-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends openjdk-21-jre-headless && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY data_engineering/ ./data_engineering/
COPY dashboard/ ./dashboard/

ENV PYTHONPATH=/app
ENV SPARK_HOME=/usr/local/lib/python3.10/site-packages/pyspark

CMD ["python", "data_engineering/loading/load_bart.py"]
